from time import sleep

print("Preparar fideus yakisoba vegetals")
sleep(1)

def recopilar_ingredients():
   print("1. Recopilar ingredients")
   sleep(1)
   print("\t1.1 Comprar al supermercat")
   sleep(1)
   print("\t1.2 Disposar-los sobre el marbre")
   sleep(1)
def cuinar_tallarines():
    print("2. Cuinar tallarines")
    sleep(1)
    print("\t2.1 Preparar aigua")
    sleep(1)
    print("\t\t2.1.1 Escalfar aigua")
    print("\t\t2.1.2 Posar-hi sal")
    sleep(1)
    print("\t2.2 Bullir tallarines")
    sleep(1)
    print("\t2.3 Escórrer tallarines")
    sleep(1)
    print("\t2.4 Deixar-les preparedes")
    sleep(1)
def cuinar_pastanagues():
    print("3. Cuinar pastanagues")
    sleep(1)
    print("\t3.1 Tallar pastanagues")
    sleep(1)
    print("\t3.2 Fregir pastanagues")
    sleep(1)
    print("\t\t3.2.1 Preparar paella per fregir")
    print("\t\t3.2.2 Rossegar pastanagues")
    print("\t\t3.2.3 Netejar oli de paella")
    sleep(1)
    print("\t3.3 Deixar pastanagues preparades")
    sleep(1)
def cuinar_cebes():
    print("4. Cuinar cebes")
    sleep(1)
    print("\t4.1 Tallar cebes")
    sleep(1)
    print("\t4.2 Fregir cebes")
    sleep(1)
    print("\t\t4.2.1 Preparar paella per fregir")
    print("\t\t4.2.2 Rossejar cebes")
    print("\t\t4.2.3 Netejar oli paella")
    sleep(1)
    print("\t4.3 Deixar cebes preparades")
    sleep(1)
def preparacio_final():
    print("5. Preparació final")
    sleep(1)
    print("\t5.1 Barrejar ingredients amb salsa yakisoba")
    sleep(1)
    print("\t5.2 Saltar ingredients")
    sleep(1)
    print("\t\t5.2.1 Preparar paella per saltar")
    print("\t\t5.2.2 Cuinar remenant ingredients")
    sleep(1)
    print("\t5.3 Deixar llest per servir")

recopilar_ingredients()
cuinar_tallarines()
cuinar_pastanagues()
preparacio_final()